name: wise_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - papermill
  - ipykernel
  - ipywidgets
  - nutpie
  - jax
  - numba
  - pip:
      - git+https://github.com/pymc-labs/pymc-marketing.git
