name: sagemaker-base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jax
  - jaxlib
  - numba
  - nutpie
  - pytensor
  - pymc
  - ipywidgets
  - ipykernel
  - pip:
    - numpyro