name: sagemaker-base-gpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jax
  - jaxlib=*=cuda12*
  - numba
  - nutpie
  - pytensor
  - pymc
  - ipywidgets
  - ipykernel
  - pip:
    - numpyro